/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedStudentsRouteImport } from './routes/_authenticated/students'
import { Route as AuthenticatedSlipRequestsRouteImport } from './routes/_authenticated/slip-requests'
import { Route as AuthenticatedSlipHistoryRouteImport } from './routes/_authenticated/slip-history'
import { Route as AuthenticatedSlipRouteImport } from './routes/_authenticated/slip'
import { Route as AuthenticatedSheetsRouteImport } from './routes/_authenticated/sheets'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedScheduleWiseRouteImport } from './routes/_authenticated/schedule-wise'
import { Route as AuthenticatedQaRouteImport } from './routes/_authenticated/qa'
import { Route as AuthenticatedPerformanceReportRouteImport } from './routes/_authenticated/performance-report'
import { Route as AuthenticatedNoticesRouteImport } from './routes/_authenticated/notices'
import { Route as AuthenticatedMonthlyReportRouteImport } from './routes/_authenticated/monthly-report'
import { Route as AuthenticatedLeaveSlipRequestsRouteImport } from './routes/_authenticated/leave-slip-requests'
import { Route as AuthenticatedLeaveSlipHistoryRouteImport } from './routes/_authenticated/leave-slip-history'
import { Route as AuthenticatedLeaveSlipRouteImport } from './routes/_authenticated/leave-slip'
import { Route as AuthenticatedLeaveReportRouteImport } from './routes/_authenticated/leave-report'
import { Route as AuthenticatedGroupSummaryRouteImport } from './routes/_authenticated/group-summary'
import { Route as AuthenticatedGroupReportRouteImport } from './routes/_authenticated/group-report'
import { Route as AuthenticatedGatePassRequestsRouteImport } from './routes/_authenticated/gate-pass-requests'
import { Route as AuthenticatedGatePassHistoryRouteImport } from './routes/_authenticated/gate-pass-history'
import { Route as AuthenticatedGatePassRouteImport } from './routes/_authenticated/gate-pass'
import { Route as AuthenticatedDecDay2RouteImport } from './routes/_authenticated/dec-day-2'
import { Route as AuthenticatedDecDay1RouteImport } from './routes/_authenticated/dec-day-1'
import { Route as AuthenticatedDailyRouteImport } from './routes/_authenticated/daily'
import { Route as AuthenticatedAttendanceRouteImport } from './routes/_authenticated/attendance'
import { Route as ApiPublicHooksRebuildSheetsRouteImport } from './routes/api/public/hooks/rebuild-sheets'
import { Route as ApiPublicGoogleCallbackRouteImport } from './routes/api/public/google/callback'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStudentsRoute = AuthenticatedStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSlipRequestsRoute =
  AuthenticatedSlipRequestsRouteImport.update({
    id: '/slip-requests',
    path: '/slip-requests',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSlipHistoryRoute =
  AuthenticatedSlipHistoryRouteImport.update({
    id: '/slip-history',
    path: '/slip-history',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSlipRoute = AuthenticatedSlipRouteImport.update({
  id: '/slip',
  path: '/slip',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSheetsRoute = AuthenticatedSheetsRouteImport.update({
  id: '/sheets',
  path: '/sheets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScheduleWiseRoute =
  AuthenticatedScheduleWiseRouteImport.update({
    id: '/schedule-wise',
    path: '/schedule-wise',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedQaRoute = AuthenticatedQaRouteImport.update({
  id: '/qa',
  path: '/qa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerformanceReportRoute =
  AuthenticatedPerformanceReportRouteImport.update({
    id: '/performance-report',
    path: '/performance-report',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNoticesRoute = AuthenticatedNoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMonthlyReportRoute =
  AuthenticatedMonthlyReportRouteImport.update({
    id: '/monthly-report',
    path: '/monthly-report',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLeaveSlipRequestsRoute =
  AuthenticatedLeaveSlipRequestsRouteImport.update({
    id: '/leave-slip-requests',
    path: '/leave-slip-requests',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLeaveSlipHistoryRoute =
  AuthenticatedLeaveSlipHistoryRouteImport.update({
    id: '/leave-slip-history',
    path: '/leave-slip-history',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLeaveSlipRoute = AuthenticatedLeaveSlipRouteImport.update({
  id: '/leave-slip',
  path: '/leave-slip',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeaveReportRoute =
  AuthenticatedLeaveReportRouteImport.update({
    id: '/leave-report',
    path: '/leave-report',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGroupSummaryRoute =
  AuthenticatedGroupSummaryRouteImport.update({
    id: '/group-summary',
    path: '/group-summary',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGroupReportRoute =
  AuthenticatedGroupReportRouteImport.update({
    id: '/group-report',
    path: '/group-report',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGatePassRequestsRoute =
  AuthenticatedGatePassRequestsRouteImport.update({
    id: '/gate-pass-requests',
    path: '/gate-pass-requests',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGatePassHistoryRoute =
  AuthenticatedGatePassHistoryRouteImport.update({
    id: '/gate-pass-history',
    path: '/gate-pass-history',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGatePassRoute = AuthenticatedGatePassRouteImport.update({
  id: '/gate-pass',
  path: '/gate-pass',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDecDay2Route = AuthenticatedDecDay2RouteImport.update({
  id: '/dec-day-2',
  path: '/dec-day-2',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDecDay1Route = AuthenticatedDecDay1RouteImport.update({
  id: '/dec-day-1',
  path: '/dec-day-1',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDailyRoute = AuthenticatedDailyRouteImport.update({
  id: '/daily',
  path: '/daily',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAttendanceRoute = AuthenticatedAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicHooksRebuildSheetsRoute =
  ApiPublicHooksRebuildSheetsRouteImport.update({
    id: '/api/public/hooks/rebuild-sheets',
    path: '/api/public/hooks/rebuild-sheets',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicGoogleCallbackRoute = ApiPublicGoogleCallbackRouteImport.update({
  id: '/api/public/google/callback',
  path: '/api/public/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/daily': typeof AuthenticatedDailyRoute
  '/dec-day-1': typeof AuthenticatedDecDay1Route
  '/dec-day-2': typeof AuthenticatedDecDay2Route
  '/gate-pass': typeof AuthenticatedGatePassRoute
  '/gate-pass-history': typeof AuthenticatedGatePassHistoryRoute
  '/gate-pass-requests': typeof AuthenticatedGatePassRequestsRoute
  '/group-report': typeof AuthenticatedGroupReportRoute
  '/group-summary': typeof AuthenticatedGroupSummaryRoute
  '/leave-report': typeof AuthenticatedLeaveReportRoute
  '/leave-slip': typeof AuthenticatedLeaveSlipRoute
  '/leave-slip-history': typeof AuthenticatedLeaveSlipHistoryRoute
  '/leave-slip-requests': typeof AuthenticatedLeaveSlipRequestsRoute
  '/monthly-report': typeof AuthenticatedMonthlyReportRoute
  '/notices': typeof AuthenticatedNoticesRoute
  '/performance-report': typeof AuthenticatedPerformanceReportRoute
  '/qa': typeof AuthenticatedQaRoute
  '/schedule-wise': typeof AuthenticatedScheduleWiseRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/sheets': typeof AuthenticatedSheetsRoute
  '/slip': typeof AuthenticatedSlipRoute
  '/slip-history': typeof AuthenticatedSlipHistoryRoute
  '/slip-requests': typeof AuthenticatedSlipRequestsRoute
  '/students': typeof AuthenticatedStudentsRoute
  '/api/public/google/callback': typeof ApiPublicGoogleCallbackRoute
  '/api/public/hooks/rebuild-sheets': typeof ApiPublicHooksRebuildSheetsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/daily': typeof AuthenticatedDailyRoute
  '/dec-day-1': typeof AuthenticatedDecDay1Route
  '/dec-day-2': typeof AuthenticatedDecDay2Route
  '/gate-pass': typeof AuthenticatedGatePassRoute
  '/gate-pass-history': typeof AuthenticatedGatePassHistoryRoute
  '/gate-pass-requests': typeof AuthenticatedGatePassRequestsRoute
  '/group-report': typeof AuthenticatedGroupReportRoute
  '/group-summary': typeof AuthenticatedGroupSummaryRoute
  '/leave-report': typeof AuthenticatedLeaveReportRoute
  '/leave-slip': typeof AuthenticatedLeaveSlipRoute
  '/leave-slip-history': typeof AuthenticatedLeaveSlipHistoryRoute
  '/leave-slip-requests': typeof AuthenticatedLeaveSlipRequestsRoute
  '/monthly-report': typeof AuthenticatedMonthlyReportRoute
  '/notices': typeof AuthenticatedNoticesRoute
  '/performance-report': typeof AuthenticatedPerformanceReportRoute
  '/qa': typeof AuthenticatedQaRoute
  '/schedule-wise': typeof AuthenticatedScheduleWiseRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/sheets': typeof AuthenticatedSheetsRoute
  '/slip': typeof AuthenticatedSlipRoute
  '/slip-history': typeof AuthenticatedSlipHistoryRoute
  '/slip-requests': typeof AuthenticatedSlipRequestsRoute
  '/students': typeof AuthenticatedStudentsRoute
  '/api/public/google/callback': typeof ApiPublicGoogleCallbackRoute
  '/api/public/hooks/rebuild-sheets': typeof ApiPublicHooksRebuildSheetsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/attendance': typeof AuthenticatedAttendanceRoute
  '/_authenticated/daily': typeof AuthenticatedDailyRoute
  '/_authenticated/dec-day-1': typeof AuthenticatedDecDay1Route
  '/_authenticated/dec-day-2': typeof AuthenticatedDecDay2Route
  '/_authenticated/gate-pass': typeof AuthenticatedGatePassRoute
  '/_authenticated/gate-pass-history': typeof AuthenticatedGatePassHistoryRoute
  '/_authenticated/gate-pass-requests': typeof AuthenticatedGatePassRequestsRoute
  '/_authenticated/group-report': typeof AuthenticatedGroupReportRoute
  '/_authenticated/group-summary': typeof AuthenticatedGroupSummaryRoute
  '/_authenticated/leave-report': typeof AuthenticatedLeaveReportRoute
  '/_authenticated/leave-slip': typeof AuthenticatedLeaveSlipRoute
  '/_authenticated/leave-slip-history': typeof AuthenticatedLeaveSlipHistoryRoute
  '/_authenticated/leave-slip-requests': typeof AuthenticatedLeaveSlipRequestsRoute
  '/_authenticated/monthly-report': typeof AuthenticatedMonthlyReportRoute
  '/_authenticated/notices': typeof AuthenticatedNoticesRoute
  '/_authenticated/performance-report': typeof AuthenticatedPerformanceReportRoute
  '/_authenticated/qa': typeof AuthenticatedQaRoute
  '/_authenticated/schedule-wise': typeof AuthenticatedScheduleWiseRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/sheets': typeof AuthenticatedSheetsRoute
  '/_authenticated/slip': typeof AuthenticatedSlipRoute
  '/_authenticated/slip-history': typeof AuthenticatedSlipHistoryRoute
  '/_authenticated/slip-requests': typeof AuthenticatedSlipRequestsRoute
  '/_authenticated/students': typeof AuthenticatedStudentsRoute
  '/api/public/google/callback': typeof ApiPublicGoogleCallbackRoute
  '/api/public/hooks/rebuild-sheets': typeof ApiPublicHooksRebuildSheetsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/attendance'
    | '/daily'
    | '/dec-day-1'
    | '/dec-day-2'
    | '/gate-pass'
    | '/gate-pass-history'
    | '/gate-pass-requests'
    | '/group-report'
    | '/group-summary'
    | '/leave-report'
    | '/leave-slip'
    | '/leave-slip-history'
    | '/leave-slip-requests'
    | '/monthly-report'
    | '/notices'
    | '/performance-report'
    | '/qa'
    | '/schedule-wise'
    | '/settings'
    | '/sheets'
    | '/slip'
    | '/slip-history'
    | '/slip-requests'
    | '/students'
    | '/api/public/google/callback'
    | '/api/public/hooks/rebuild-sheets'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/attendance'
    | '/daily'
    | '/dec-day-1'
    | '/dec-day-2'
    | '/gate-pass'
    | '/gate-pass-history'
    | '/gate-pass-requests'
    | '/group-report'
    | '/group-summary'
    | '/leave-report'
    | '/leave-slip'
    | '/leave-slip-history'
    | '/leave-slip-requests'
    | '/monthly-report'
    | '/notices'
    | '/performance-report'
    | '/qa'
    | '/schedule-wise'
    | '/settings'
    | '/sheets'
    | '/slip'
    | '/slip-history'
    | '/slip-requests'
    | '/students'
    | '/api/public/google/callback'
    | '/api/public/hooks/rebuild-sheets'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/attendance'
    | '/_authenticated/daily'
    | '/_authenticated/dec-day-1'
    | '/_authenticated/dec-day-2'
    | '/_authenticated/gate-pass'
    | '/_authenticated/gate-pass-history'
    | '/_authenticated/gate-pass-requests'
    | '/_authenticated/group-report'
    | '/_authenticated/group-summary'
    | '/_authenticated/leave-report'
    | '/_authenticated/leave-slip'
    | '/_authenticated/leave-slip-history'
    | '/_authenticated/leave-slip-requests'
    | '/_authenticated/monthly-report'
    | '/_authenticated/notices'
    | '/_authenticated/performance-report'
    | '/_authenticated/qa'
    | '/_authenticated/schedule-wise'
    | '/_authenticated/settings'
    | '/_authenticated/sheets'
    | '/_authenticated/slip'
    | '/_authenticated/slip-history'
    | '/_authenticated/slip-requests'
    | '/_authenticated/students'
    | '/api/public/google/callback'
    | '/api/public/hooks/rebuild-sheets'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicGoogleCallbackRoute: typeof ApiPublicGoogleCallbackRoute
  ApiPublicHooksRebuildSheetsRoute: typeof ApiPublicHooksRebuildSheetsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/students': {
      id: '/_authenticated/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AuthenticatedStudentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/slip-requests': {
      id: '/_authenticated/slip-requests'
      path: '/slip-requests'
      fullPath: '/slip-requests'
      preLoaderRoute: typeof AuthenticatedSlipRequestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/slip-history': {
      id: '/_authenticated/slip-history'
      path: '/slip-history'
      fullPath: '/slip-history'
      preLoaderRoute: typeof AuthenticatedSlipHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/slip': {
      id: '/_authenticated/slip'
      path: '/slip'
      fullPath: '/slip'
      preLoaderRoute: typeof AuthenticatedSlipRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sheets': {
      id: '/_authenticated/sheets'
      path: '/sheets'
      fullPath: '/sheets'
      preLoaderRoute: typeof AuthenticatedSheetsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/schedule-wise': {
      id: '/_authenticated/schedule-wise'
      path: '/schedule-wise'
      fullPath: '/schedule-wise'
      preLoaderRoute: typeof AuthenticatedScheduleWiseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/qa': {
      id: '/_authenticated/qa'
      path: '/qa'
      fullPath: '/qa'
      preLoaderRoute: typeof AuthenticatedQaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/performance-report': {
      id: '/_authenticated/performance-report'
      path: '/performance-report'
      fullPath: '/performance-report'
      preLoaderRoute: typeof AuthenticatedPerformanceReportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notices': {
      id: '/_authenticated/notices'
      path: '/notices'
      fullPath: '/notices'
      preLoaderRoute: typeof AuthenticatedNoticesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/monthly-report': {
      id: '/_authenticated/monthly-report'
      path: '/monthly-report'
      fullPath: '/monthly-report'
      preLoaderRoute: typeof AuthenticatedMonthlyReportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leave-slip-requests': {
      id: '/_authenticated/leave-slip-requests'
      path: '/leave-slip-requests'
      fullPath: '/leave-slip-requests'
      preLoaderRoute: typeof AuthenticatedLeaveSlipRequestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leave-slip-history': {
      id: '/_authenticated/leave-slip-history'
      path: '/leave-slip-history'
      fullPath: '/leave-slip-history'
      preLoaderRoute: typeof AuthenticatedLeaveSlipHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leave-slip': {
      id: '/_authenticated/leave-slip'
      path: '/leave-slip'
      fullPath: '/leave-slip'
      preLoaderRoute: typeof AuthenticatedLeaveSlipRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leave-report': {
      id: '/_authenticated/leave-report'
      path: '/leave-report'
      fullPath: '/leave-report'
      preLoaderRoute: typeof AuthenticatedLeaveReportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/group-summary': {
      id: '/_authenticated/group-summary'
      path: '/group-summary'
      fullPath: '/group-summary'
      preLoaderRoute: typeof AuthenticatedGroupSummaryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/group-report': {
      id: '/_authenticated/group-report'
      path: '/group-report'
      fullPath: '/group-report'
      preLoaderRoute: typeof AuthenticatedGroupReportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gate-pass-requests': {
      id: '/_authenticated/gate-pass-requests'
      path: '/gate-pass-requests'
      fullPath: '/gate-pass-requests'
      preLoaderRoute: typeof AuthenticatedGatePassRequestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gate-pass-history': {
      id: '/_authenticated/gate-pass-history'
      path: '/gate-pass-history'
      fullPath: '/gate-pass-history'
      preLoaderRoute: typeof AuthenticatedGatePassHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gate-pass': {
      id: '/_authenticated/gate-pass'
      path: '/gate-pass'
      fullPath: '/gate-pass'
      preLoaderRoute: typeof AuthenticatedGatePassRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dec-day-2': {
      id: '/_authenticated/dec-day-2'
      path: '/dec-day-2'
      fullPath: '/dec-day-2'
      preLoaderRoute: typeof AuthenticatedDecDay2RouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dec-day-1': {
      id: '/_authenticated/dec-day-1'
      path: '/dec-day-1'
      fullPath: '/dec-day-1'
      preLoaderRoute: typeof AuthenticatedDecDay1RouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/daily': {
      id: '/_authenticated/daily'
      path: '/daily'
      fullPath: '/daily'
      preLoaderRoute: typeof AuthenticatedDailyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attendance': {
      id: '/_authenticated/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AuthenticatedAttendanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/rebuild-sheets': {
      id: '/api/public/hooks/rebuild-sheets'
      path: '/api/public/hooks/rebuild-sheets'
      fullPath: '/api/public/hooks/rebuild-sheets'
      preLoaderRoute: typeof ApiPublicHooksRebuildSheetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/google/callback': {
      id: '/api/public/google/callback'
      path: '/api/public/google/callback'
      fullPath: '/api/public/google/callback'
      preLoaderRoute: typeof ApiPublicGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAttendanceRoute: typeof AuthenticatedAttendanceRoute
  AuthenticatedDailyRoute: typeof AuthenticatedDailyRoute
  AuthenticatedDecDay1Route: typeof AuthenticatedDecDay1Route
  AuthenticatedDecDay2Route: typeof AuthenticatedDecDay2Route
  AuthenticatedGatePassRoute: typeof AuthenticatedGatePassRoute
  AuthenticatedGatePassHistoryRoute: typeof AuthenticatedGatePassHistoryRoute
  AuthenticatedGatePassRequestsRoute: typeof AuthenticatedGatePassRequestsRoute
  AuthenticatedGroupReportRoute: typeof AuthenticatedGroupReportRoute
  AuthenticatedGroupSummaryRoute: typeof AuthenticatedGroupSummaryRoute
  AuthenticatedLeaveReportRoute: typeof AuthenticatedLeaveReportRoute
  AuthenticatedLeaveSlipRoute: typeof AuthenticatedLeaveSlipRoute
  AuthenticatedLeaveSlipHistoryRoute: typeof AuthenticatedLeaveSlipHistoryRoute
  AuthenticatedLeaveSlipRequestsRoute: typeof AuthenticatedLeaveSlipRequestsRoute
  AuthenticatedMonthlyReportRoute: typeof AuthenticatedMonthlyReportRoute
  AuthenticatedNoticesRoute: typeof AuthenticatedNoticesRoute
  AuthenticatedPerformanceReportRoute: typeof AuthenticatedPerformanceReportRoute
  AuthenticatedQaRoute: typeof AuthenticatedQaRoute
  AuthenticatedScheduleWiseRoute: typeof AuthenticatedScheduleWiseRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSheetsRoute: typeof AuthenticatedSheetsRoute
  AuthenticatedSlipRoute: typeof AuthenticatedSlipRoute
  AuthenticatedSlipHistoryRoute: typeof AuthenticatedSlipHistoryRoute
  AuthenticatedSlipRequestsRoute: typeof AuthenticatedSlipRequestsRoute
  AuthenticatedStudentsRoute: typeof AuthenticatedStudentsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAttendanceRoute: AuthenticatedAttendanceRoute,
  AuthenticatedDailyRoute: AuthenticatedDailyRoute,
  AuthenticatedDecDay1Route: AuthenticatedDecDay1Route,
  AuthenticatedDecDay2Route: AuthenticatedDecDay2Route,
  AuthenticatedGatePassRoute: AuthenticatedGatePassRoute,
  AuthenticatedGatePassHistoryRoute: AuthenticatedGatePassHistoryRoute,
  AuthenticatedGatePassRequestsRoute: AuthenticatedGatePassRequestsRoute,
  AuthenticatedGroupReportRoute: AuthenticatedGroupReportRoute,
  AuthenticatedGroupSummaryRoute: AuthenticatedGroupSummaryRoute,
  AuthenticatedLeaveReportRoute: AuthenticatedLeaveReportRoute,
  AuthenticatedLeaveSlipRoute: AuthenticatedLeaveSlipRoute,
  AuthenticatedLeaveSlipHistoryRoute: AuthenticatedLeaveSlipHistoryRoute,
  AuthenticatedLeaveSlipRequestsRoute: AuthenticatedLeaveSlipRequestsRoute,
  AuthenticatedMonthlyReportRoute: AuthenticatedMonthlyReportRoute,
  AuthenticatedNoticesRoute: AuthenticatedNoticesRoute,
  AuthenticatedPerformanceReportRoute: AuthenticatedPerformanceReportRoute,
  AuthenticatedQaRoute: AuthenticatedQaRoute,
  AuthenticatedScheduleWiseRoute: AuthenticatedScheduleWiseRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSheetsRoute: AuthenticatedSheetsRoute,
  AuthenticatedSlipRoute: AuthenticatedSlipRoute,
  AuthenticatedSlipHistoryRoute: AuthenticatedSlipHistoryRoute,
  AuthenticatedSlipRequestsRoute: AuthenticatedSlipRequestsRoute,
  AuthenticatedStudentsRoute: AuthenticatedStudentsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicGoogleCallbackRoute: ApiPublicGoogleCallbackRoute,
  ApiPublicHooksRebuildSheetsRoute: ApiPublicHooksRebuildSheetsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
